### ISSUE TITLE
USB Device not recognized

### ISSUE THREAD

**Issue by Zentelechia** [J-Rios/Digispark_DigiUSB-SoftSerial#1]
Hi!

I've made all as you described, but still get message "USB Device not regognized" when attache Diispark to usb.  P2 and P3 connected together.

In what direction should I dig?

**Comment by J-Rios** [comment]
Hi,

Take care that "USB device not recognized" is showed when the digispark can't establish or maintain alive the USB communication with the host (PC).

To maintain the communication, it is vital use in your code:
- DigiMouse/DigiKeyboard.delay() instead arduino delay (if you need a delay)
- DigiMouse/DigiKeyboard.update() in the loop function (still alive)

You can try this code to make sure that the library is setting up correctly:

```
#include <TinyPinChange.h>
#include <SoftSerial.h>
#include <DigiMouse.h>

#define P_RX 0
#define P_TX 1

SoftSerial myuart(P_RX, P_TX);

void setup()
{
    myuart.begin(9600);
    DigiMouse.begin();
}

void loop()
{
    DigiMouse.update();
}
```

**Comment by Yoobe** [comment]
J-Rios,

did you tried to compile this code?
I have a conflict 

C:\Users\xx\AppData\Local\Temp\build6279310120158104946.tmp\DigisparkMouse\usbdrvasm.S.o: In function `__vector_2':
C:\Users\xx\AppData\Roaming\Arduino15\packages\digistump\hardware\avr\1.6.5\libraries\DigisparkMouse/usbdrvasm165.inc:41: multiple definition of `__vector_2'
C:\Users\xx\AppData\Local\Temp\build6279310120158104946.tmp\DigisparkTinyPinChange\TinyPinChange.cpp.o:C:\Users\Baris\AppData\Roaming\Arduino15\packages\digistump\hardware\avr\1.6.5\libraries\DigisparkTinyPinChange/TinyPinChange.cpp:57: first defined here
collect2.exe: error: ld returned 1 exit status
Error compiling.
